---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest@sha256:0def896a596e8d45780b6359dbf82fc8c75ef05b97e095452e67a0a4ccc95377
    environment:
      WEBPASSWORD: admin
    ports:
      - 80:80
    volumes:
      - ./var/docker/pihole/etc:/etc/pihole
      - ./var/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    labels:
      dockerdns.pihole.cname.domain: pihole.home.lan
      dockerdns.pihole.cname.target: server.home.lan

  whoami:
    container_name: whoami
    image: traefik/whoami@sha256:43a68d10b9dfcfc3ffbfe4dd42100dc9aeaf29b3a5636c856337a5940f1b4f1c
    command:
      - --name=whoami
    ports:
      - 8080:80
    labels:
      dockerdns.pihole.cname.domain: whoami.home.lan
      dockerdns.pihole.cname.target: server.home.lan
      dockerdns.pihole.cname.0.domain: whoami1.home.lan
      dockerdns.pihole.cname.0.target: server.home.lan
      dockerdns.pihole.cname.1.domain: whoami2.home.lan
      dockerdns.pihole.cname.1.target: server.home.lan
