---
version: 3

tasks:
  deps:
    desc: install dependencies
    cmds:
      - task -l
      #- curl -fsSL https://goss.rocks/install | sudo sh

  compose:start:
    desc: Start compose services
    cmd: docker compose up -d

  compose:stop:
    desc: stop compose containers
    cmd: docker compose stop

  compose:rm:
    desc: remove compose containers
    cmd: docker compose rm --force

  compose:recreate:
    desc: recreate compose containers
    cmds:
      - task: compose:stop
      - task: compose:rm
      - task: compose:start

  coverage:
    desc: run phpunit with coverage text
    cmd: ./vendor/bin/phpunit --coverage-text

  build:
    desc: build docker file
    cmd: docker build -t docker-dns:testing .

  goss:
    desc: run goss test
    cmds:
      - task: build
      - dgoss run -v /var/run/docker.sock:/var/run/docker.sock docker-dns:testing
    env:
      APP_ENV: prod
      GOSS_FILE: ./docker/goss.yaml
      GOSS_FILES_STRATEGY: cp
      GOSS_OPTS: --sleep 5s --retry-timeout 60s --color --format documentation
      GOSS_SLEEP: 2
      DOCKERDNS_PIHOLE_URL: http://localhost
      DOCKERDNS_PIHOLE_TOKEN: 998ed4d621742d0c2d85ed84173db569afa194d4597686cae947324aa58ab4bb
